# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestDemo
  pod 'LFYGroupAvatar', :path => '../LFYGroupAvatarLib'
  target 'TestDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
